---
version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: base
    command: "debug"
    volumes:
      - ./api/src:/usr/api/src
      - ./api/ormconfig.ts:/usr/api/ormconfig.ts
      - ./api/package.json:/usr/api/package.json
    ports:
      - '4101:3000'
      - '9229:9229'

