---
version: '3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    command: "debug"
    volumes:
      - ./src:/usr/api/src
    env_file:
      - ./app.env
    ports:
      - '4101:3000'
      - '9229:9229'

